### ISSUE TITLE
Add website design using www.uxpin.com

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#12]
We need an overall design for the site. There are over 100 routes for the Miami Transit system. Eventually, there will be too much data to display. We need a user interface design to handle all this.

https://www.uxpin.com
Using UXPin was mentioned by Aris from Live Ninja who was at the Meetup.

**Comment by ErnieAtLYD** [comment]
Hey, I can try my best to take a stab at this but this will literally be a side project of a side project due to all the stuff I'm doing as a fellow. Also - if you have a designer at the weekly Monday meetings who is itching to work on this I will give priority to them.

**Comment by qtrandev** [comment]
Let's leave it unassigned until have a regular designer to talk to. There's no one I know who wants to do this yet.

**Comment by ErnieAtLYD** [comment]
So I've got three major things in mind:

- Make the map prettier
- Make a way to toggle (or remove?) some of the cruft like landmarks or bus stops which look super large when zoomed way out
- Make all transit agency lines one color (so bus lines are a color) which should make it looks like a rainbow threw up on an OpenStreetMap. ;)

**Comment by qtrandev** [comment]
For landmarks and bus stops which looks too big right now when zoomed out, I'm hoping to find a way to only show the big icons when zoomed in to a certain level (such as 16 out of max 20) when there's not too many other icons on the map. I think there's a way in Leaflet to render objects depending on what zoom level it is. This can be a separate Github issue/improvement to work on.

Making the transit agency lines all one color is something to work on in #5. We'll need to think out which color to set each though first. I can then create color constants in the beginning of the code that we can easily change. I'd like to somehow show the route colors somewhere - so maybe in the popup when user selects a bus stop or bus.

**Comment by qtrandev** [comment]
This issue was moved to Code-for-Miami/LeafletTransit#6
