### ISSUE TITLE
Citi bikes are not showing - find out why

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#13]
The API could be down or blocked or there may be a bug. Investigate.

**Comment by qtrandev** [comment]
Even the Citi Bikes website is not showing the bike locations:
http://citibikemiami.com/station-map

The API returns an empty xml:
http://citibikemiami.com/downtown-miami-locations.xml

**Comment by qtrandev** [comment]
Any way to report to Citi Bike Miami that their map is not working? http://citibikemiami.com/station-map

**Comment by ErnieAtLYD** [comment]
I'll reach out to them and figure out what's up. My only contact is through their Facebook message.

**Comment by qtrandev** [comment]
The bikes have appeared again. Thanks!

**Comment by ErnieAtLYD** [comment]
:+1:
