### ISSUE TITLE
Investigate trolleys in other cities

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#19]
This is a work item to investigate what trolley services and locations are available in South Florida cities. Start with the following cities and organizations:

City of Aventura Transit
Broward County Transit
City of Coral Gables Trolleys
Town of Cutler Bay
City of Hialeah Transit System
Jitney Transfers
Tri-Rail Transfers

This list shows an overview of those systems above: http://www.miamidade.gov/transit/transfers-outside-mdt.asp

### Aventura
Aventura Express Shuttle Bus - http://www.cityofaventura.com/index.aspx?page=121
Route map PDF - http://www.cityofaventura.com/modules/showdocument.aspx?documentid=351
Schedule PDF - http://www.cityofaventura.com/modules/showdocument.aspx?documentid=352
There is no online map or live data.

### Broward County Transit
Website - http://www.broward.org/BCT/Pages/default.aspx
Google Transit GTFS Feed - http://www.broward.org/bct/google/latest/google_transit.zip
Schedules - http://www.broward.org/BCT/Schedules/Pages/default.aspx
System map PDF - http://www.broward.org/BCT/Documents/SystemMap.pdf
There is no live data but I heard from a BCT contractor who came once to a Code For Miami meeting that upgrades are in process and live video and GPS data are being added - no info on completion date.

### Coral Gables
Website - http://www.coralgables.com/index.aspx?page=325
Route map PDF - http://www.coralgables.com/modules/showdocument.aspx?documentid=10750
There is no online map or live data.

### Cutler Bay
Served by the Miami-Dade Transit Cutler Bay Local route:
http://www.miamidade.gov/transit/routes_detail.asp?route=200

### Hialeah 
Website - http://www.hialeahfl.gov/index.php?option=com_content&view=article&id=141&Itemid=409&lang=en
Route map PDF - http://www.hialeahfl.gov/index.php?option=com_docman&task=doc_download&gid=3956&Itemid=515
There is no online map or live data.

### Jitney Transfers
Conchita Transit Express operates a private jitney service that connects to and from the Hialeah Metrorail station.
There is no website, online map or live data.

### Tri-Rail Transfers
Website - http://www.tri-rail.com
System map PDF - http://www.tri-rail.com/train-schedules/System-Map-MIC-Future.pdf
Train schedule PDF - http://www.sfrta.fl.gov/docs/Online-Train-Schedule-April-2015-HR.pdf
Smartphone app - http://www.tri-rail.com/rider-information/smart-phone-app/
There is no online map or live data seen.

### Doral
https://github.com/qtrandev/LeafletTransit/issues/3

### Miami Beach
https://github.com/qtrandev/LeafletTransit/issues/11

### Miami Lakes
https://github.com/qtrandev/LeafletTransit/issues/18

### City of Miami
http://www.miamigov.com/trolley
http://miami.etaspot.net/
https://github.com/qtrandev/LeafletTransit/blob/master/routeCoords.json

### Hollywood
http://app.tsomobile.com/publictransportation/driverroute.htm?tkn=C6B3CFCC-C1B2-47B4-9FD3-EEFB2A46E3C6

### Palm Beach County Palm Tran
Location tracking:
http://www.palmtran.org/igo
Sample:
http://www.palmtran.org/iGo/rest/Vehicles/GetAllVehiclesForRoutes?routeIDs=2
Scripts:
http://www.palmtran.org/iGo/Scripts/myavail/MyAvail.js
http://www.palmtran.org/iGo/Scripts/myavail/desktop/MyAvail.Vehicle.js

**Comment by yamilethmedina** [comment]
Miami Gardens trolley:
http://www.miamigardens-fl.gov/publicworks/express.html
Transportation Service hours are Monday-Friday from 7am-7pm.
West map: http://www.miamigardens-fl.gov/publicworks/pdf/trolley/west-route-2015-04.pdf
East map: http://www.miamigardens-fl.gov/publicworks/pdf/trolley/east-route-2015-04.pdf
No live data.

The City of West Miami also has a trolley (i've seen signs for the West Miami hour-long loop), but there's no proof of its existence on the internet.

**Comment by qtrandev** [comment]
The information here is used to update https://github.com/Code-for-Miami/Miami-Dade-Transit-Developers/wiki/Regionwide-Transit-Agencies-and-APIs

**Comment by qtrandev** [comment]
Closing this item. Any other information found should be added to https://github.com/Code-for-Miami/Miami-Dade-Transit-Developers/wiki/Regionwide-Transit-Agencies-and-APIs
