### ISSUE TITLE
Sidebar for map

### ISSUE THREAD

**Issue by mam98222** [qtrandev/LeafletTransit#25]
Static sidebar for map ~30% on right side, remainder of page will be map.

Example, google maps classic:
https://maps.google.com/maps/mm

**Comment by mam98222** [comment]
Wireframe editor... Let's see if we can find a better site
http://gridpapr.com/edit/bbb16ca414a276bdd83fab63a088d191

**Comment by qtrandev** [comment]
This issue was moved to Code-for-Miami/LeafletTransit#11
