### ISSUE TITLE
User interface improvements

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#27]

**Comment by GiovannaG** [comment]
![webpage1](https://cloud.githubusercontent.com/assets/11933593/7577806/a3b8ea7e-f81a-11e4-99e8-d2746c4e4a8d.JPG)

**Comment by qtrandev** [comment]
This is the initial interface. We want to make it better.

**Comment by GiovannaG** [comment]
![possible interface 1_web](https://cloud.githubusercontent.com/assets/11933593/7692978/7c25a3e8-fd98-11e4-86ba-2f77cb08298f.jpg)
![possible interface 2_web](https://cloud.githubusercontent.com/assets/11933593/7692979/7c328022-fd98-11e4-8c32-798a7875d4c0.jpg)

**Comment by GiovannaG** [comment]
![mobile interface_possible 1](https://cloud.githubusercontent.com/assets/11933593/7693288/352de9e6-fd9d-11e4-90f9-8be0e9f30472.jpg)
![mobile interface_possible 2](https://cloud.githubusercontent.com/assets/11933593/7693289/352e0c6e-fd9d-11e4-928e-013b525c193e.jpg)

**Comment by GiovannaG** [comment]
![mobile interface_possible 0_1-05](https://cloud.githubusercontent.com/assets/11933593/7693564/5be9648a-fda1-11e4-8dda-c7c2b53157ec.jpg)

**Comment by qtrandev** [comment]
This issue was moved to Code-for-Miami/LeafletTransit#12
