### ISSUE TITLE
Add the City of Doral trolleys

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#3]
Doral Trolley: http://www.cityofdoral.com/index.php?option=com_content&view=article&id=149&Itemid=339

Map: http://app.tsomobile.com/publictransportation/driverroute.htm?tkn=582EB861-9C13-4C89-B491-15F0AFBF9F47
During the day, the trolleys are on the maps. During the night, they may disappear. There are about 7 trolleys seen: DT01, DT03, DT05, DT06, DT07, DT09, DT0B, etc.

Main Javascript files seen:
http://app.tsomobile.com/publictransportation/driverroute.js
http://app.tsomobile.com/core/db/dbLib.js

This link returns the following data: http://rest.tsoapi.com//MappingController/GetUnitFromRouteAntibunching?callback=jQuery19103252993382047862_1427862361188&tkn=582EB861-9C13-4C89-B491-15F0AFBF9F47&geofencesid=35929&lan=en&_=1427862361294

jQuery19103252993382047862_1427862361188("{\"Units\":[{\"MarkerID\":\"1022582\",\"MarkerName\":\"DT0C\",\"Latitude\":\"25.811438\",\"Longitude\":\"-80.239133\",\"Direction\":\"NE\",\"Heading\":\"52\"},{\"MarkerID\":\"1002749\",\"MarkerName\":\"DT0B\",\"Latitude\":\"25.823312\",\"Longitude\":\"-80.369868\",\"Direction\":\"S\",\"Heading\":\"167\"},{\"MarkerID\":\"1005858\",\"MarkerName\":\"DT09\",\"Latitude\":\"25.851035\",\"Longitude\":\"-80.370776\",\"Direction\":\"N\",\"Heading\":\"0\"},{\"MarkerID\":\"1012049\",\"MarkerName\":\"DT05\",\"Latitude\":\"25.789840\",\"Longitude\":\"-80.334141\",\"Direction\":\"E\",\"Heading\":\"89\"},{\"MarkerID\":\"1012059\",\"MarkerName\":\"DT04\",\"Latitude\":\"25.811851\",\"Longitude\":\"-80.239400\",\"Direction\":\"N\",\"Heading\":\"0\"},{\"MarkerID\":\"1036382\",\"MarkerName\":\"DT03\",\"Latitude\":\"25.802444\",\"Longitude\":\"-80.369228\",\"Direction\":\"N\",\"Heading\":\"0\"}],\"antibunching\":{}}");

**Comment by ErnieAtLYD** [comment]
Nice job!

**Comment by qtrandev** [comment]
Thanks! There's still improvements I can do to it such as showing the correct direction icon and color of the icon. Create improvement issues for things you want immediately and I'll prioritize.
