### ISSUE TITLE
For the future: conside color coding all the "modes" a singular color

### ISSUE THREAD

**Issue by ErnieAtLYD** [qtrandev/LeafletTransit#5]
Meaning that the project because  more of a system map with color coded routes.

For example, all the busses are one color, metro rail is another, metromover a third, etc. It would be based on agencies, so city of Miami trolley and city of Doral trolleys would be different colors.

**Comment by qtrandev** [comment]
This issue was moved to Code-for-Miami/LeafletTransit#2
