### ISSUE TITLE
Fix blank map bug

### ISSUE THREAD

**Issue by qtrandev** [qtrandev/LeafletTransit#7]
There is a bug that only seems to happen once in a while where the map shows up as blank on load. It requires a 2nd reload to work.

It is very hard to reproduce but some people on a different might always see this and the blank map won't go away even on reload.

I suspect it's this line in index.html (line 345) in the addNearByMarker() function:
marker.on('mouseover', function (e) {
				this.openPopup();
			});

**Comment by qtrandev** [comment]
Issue is still there

**Comment by ErnieAtLYD** [comment]
Do you see this on different browser settings? Is it always on mobile, or desktop, or a combination of both?

**Comment by qtrandev** [comment]
I see this once in a while on my desktop browser Chrome on Windows 7 and I saw it on someone else's Windows computer with both Firefox and Chrome where it wouldn't load anything except the blank map. I think it happens more with transit4 and may have improved with transit5, but maybe it's some sort of timing problem where my already fragile Javascript code is being asked to do too much.

**Comment by ErnieAtLYD** [comment]
So this is what I noticed: If I got to http://qtrandev.com/transit5/ rather than http://www.qtrandev.com/transit5/ I will get the blank map with the following error messages in the Chrome log on OSX:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
index.js:141 XMLHttpRequest cannot load http://198.74.52.26/bus/livebus.php. The 'Access-Control-Allow-Origin' header has a value 'http://www.qtrandev.com' that is not equal to the supplied origin. Origin 'http://qtrandev.com' is therefore not allowed access.
index.js:141 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://198.74.52.26/bus/livebus.php'.
```

**Comment by qtrandev** [comment]
I think that may be the problem. Will make a fix tomorrow.
